language: r
sudo: required
dist: trusty
cache: packages
warnings_are_errors: false
env:
  global:
    - _R_CHECK_FORCE_SUGGESTS_="FALSE"
addons:
  apt:
    packages:
    - libudunits2-dev                     # units > ggforce > ggraph > patchwork > dynplot
install:
 - R -e 'setRepositories(ind = 1:2); devtools::install_github(c("dynverse/embeddr", "dynverse/destiny", "dynverse/GPfates", "dynverse/monocle-release", "dynverse/Mpath"))'
 - R -e 'setRepositories(ind = 1:2); devtools::install()'
r_check_args: "--no-tests --no-manual --no-vignettes --no-build-vignettes --no-examples"
r_build_args: "--no-build-vignettes"
after_success:
 - echo Init 1 succeeded!
